### PR TITLE
Use Rails 5 by default in centos7-devel

### PR DESCRIPTION
**Pull request by akofink**
To test:

```yaml
centos7-devel-test:
  box: centos7
  ansible:
    playbook: 'playbooks/devel.yml'
    group: 'devel'
    variables:
      foreman_installer_module_prs: "katello/katello_devel/140"
```

### CODE REVIEW

**Comment by ekohl** [comment]
Thanks!

**Comment by akofink** [comment]
@ekohl Did this work without errors for you?

**Comment by ekohl** [comment]
@akofink I kind of assumed you tested it. Currently on hotel wifi so not the capacity to properly test this.

**Comment by akofink** [comment]
I did test it, and it gives some errors when trying to communicate with the internal foreman proxy. I guess I should have WIP'd.

**Comment by ekohl** [comment]
Well, that's a known issue with the oauth gem. Version 0.5.4 has been released so could you retry with that?

**Comment by akofink** [comment]
It worked fine now. Thanks @ekohl!

**Pull request merged**
