### PR TITLE
Changed Puma default workers to 2

### PR DESCRIPTION
**Pull request by sthirugn**
To sync with the default Puma settings in https://github.com/theforeman/foreman/pull/7421

### CODE REVIEW

**Comment by ekohl** [comment]
Looks like the tests need an update as well

**Comment by sthirugn** [comment]
@ekohl spec tests updated.

**Comment by ekohl** [comment]
For future reference, we typically don't create Redmine issues for the devel module since it has no release cycle. There's only git master.

**Comment by sthirugn** [comment]
> For future reference, we typically don't create Redmine issues for the devel module since it has no release cycle. There's only git master.

Great thank you for the info.

**Pull request merged**
