### PR TITLE
support postgresql 12

### PR DESCRIPTION
**Pull request by jlsherrill**

### CODE REVIEW

**Comment by johnpmitsch** [comment]
I'm still [seeing errors](https://paste.centos.org/view/1b0c8f2b) when spinning up a devel box with this PR. Not sure if they have been behind the original errors or related to them, I have the box up if you need me to check anything

**Comment by johnpmitsch** [comment]
This is from journalctl when restarting postgresql:

```
Feb 03 15:44:48 centos7-katello-devel-psql.jomitsch.example.com systemd[1]: Starting PostgreSQL database server...
-- Subject: Unit postgresql.service has begun start-up
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit postgresql.service has begun starting up.
Feb 03 15:44:48 centos7-katello-devel-psql.jomitsch.example.com sh[9749]: postmaster: could not access the server configuration file "/var/opt/rh/rh-postgresql12/lib/pgsql/data/
Feb 03 15:44:48 centos7-katello-devel-psql.jomitsch.example.com systemd[1]: postgresql.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Feb 03 15:44:48 centos7-katello-devel-psql.jomitsch.example.com systemd[1]: Failed to start PostgreSQL database server.
-- Subject: Unit postgresql.service has failed
-- Defined-By: systemd
-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit postgresql.service has failed.
-- 
-- The result is failed.
```

**Comment by ehelms** [comment]
I think that is a separate issue related to SELinux. Can you confirm if SELinux is enabled? And/or if there is an audit.log denial?

**Comment by johnpmitsch** [comment]
@ehelms It does indeed look like an SELinux denial, setting SELinux to permissive allowed postgresql service to restart successfully.

Here is the audit.log entry:
```
type=AVC msg=audit(1580754912.210:3091): avc:  denied  { getattr } for  pid=10219 comm="postmaster" path="/var/opt/rh/rh-postgresql12/lib/pgsql/data/postgresql.conf" dev="vda1" ino=34088963 scontext=system_u:system_r:postgresql_t:s0 tcontext=system_u:object_r:var_t:s0 tclass=file permissive=0
type=SYSCALL msg=audit(1580754912.210:3091): arch=c000003e syscall=4 success=no exit=-13 a0=2af75e0 a1=7ffcb0ea9d90 a2=7ffcb0ea9d90 a3=2f62696c2f32316c items=0 ppid=1 pid=10219 auid=4294967295 uid=26 gid=26 euid=26 suid=26 fsuid=26 egid=26 sgid=26 fsgid=26 tty=(none) ses=4294967295 comm="postmaster" exe="/opt/rh/rh-postgresql12/root/usr/bin/postgres" subj=system_u:system_r:postgresql_t:s0 key=(null)
type=PROCTITLE msg=audit(1580754912.210:3091): proctitle=706F73746D6173746572002D44002F7661722F6F70742F72682F72682D706F737467726573716C31322F6C69622F706773716C2F64617461
type=SERVICE_START msg=audit(1580754912.215:3092): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=system_u:system_r:init_t:s0 msg='unit=postgresql comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=failed'
```

If you point me to the right place, I can help add an allow rule.

**Comment by ehelms** [comment]
We either need to disable selinux as part of (https://github.com/theforeman/forklift/blob/master/roles/katello_devel/meta/main.yml) or update the check here to include some provision for devel (https://github.com/theforeman/foreman-installer/blob/develop/hooks/pre/31-el7_install_postgresql.rb#L2).

**Pull request merged**
